---
abstract: 'A wrapper around the Jenkins API'
author:
  - 'Colin Newell, C<< <colin.newell at gmail.com> >>'
  - 'Colin Newell <colin.newell@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jenkins-API
no_index:
  directory:
    - example
    - inc
    - t
requires:
  File::ShareDir: 0
  JSON: 0
  MIME::Base64: 0
  Moose: 0
  REST::Client: 0
  URI: 0
resources:
  bugtracker: https://github.com/colinnewell/Jenkins-API/issues
  homepage: https://github.com/colinnewell/Jenkins-API
  license: http://dev.perl.org/licenses/
  repository: https://github.com/colinnewell/Jenkins-API
version: 0.05
